#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1536331909                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           :                                           # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/img/mpdpilot.jpg                   # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : MPD Pilot                                  # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Friendly Music Player Daemon controller

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 :
your_link                                 :
your_city                                 :
email_address                             : support@mpdpilot.app
facebook_username                         :                                           
instagram_username                        :
twitter_username                          : mpdpilot
github_username                           :
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : User-friendly UI
    description                           : Easy to use, convenient user interface, supporting light and dark modes.
    fontawesome_icon_name                 : magic

  - title                                 : MPD server state
    description                           : Manage playback, volume and shuffle & repeat modes. Seek to selected position of currently playing song.
    fontawesome_icon_name                 : play

  - title                                 : Queue
    description                           : Add, move and remove items from the current playback queue.
    fontawesome_icon_name                 : list

  - title                                 : Music Library
    description                           : Browse files library and enqueue songs, folders or stored playlists.
    fontawesome_icon_name                 : compact-disc

  - title                                 : Search
    description                           : Quickly find songs in your MPD collection.
    fontawesome_icon_name                 : search

  - title                                 : Local playback
    description                           : Play streaming MPD outputs locally on your speakers, bluetooth headphones or AirPlay devices.
    fontawesome_icon_name                 : headphones

  - title                                 : Easy configuration
    description                           : Connect to automatially discovered MPD servers in your local network using Bonjour protocol.
    fontawesome_icon_name                 : wifi

  - title                                 : Multiple connections
    description                           : Store credentials to multiple servers and connect with selected one.
    fontawesome_icon_name                 : network-wired

  - title                                 : Use on iPhone and iPad
    description                           : The app supports both iPhone and iPad, and requires at least iOS 15+.
    fontawesome_icon_name                 : tablet-alt


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
  - vendor/

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
