#page title
page_title                                : MPD Pilot - Friendly MPD controller for Apple devices # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1536331909                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           :                                           # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/img/mpdpilot.jpg                   # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : MPD Pilot                                  # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Friendly Music Player Daemon controller

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 :
your_link                                 :
your_city                                 :
email_address                             : support@mpdpilot.app
facebook_username                         :                                           
instagram_username                        :
twitter_username                          : mpdpilot
github_username                           :
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

- title: Beautiful, Accessible Interface
  description: MPD Pilot offers a clean, accessible design, with support for light and dark modes. Effortless to navigate, it's designed with both casual and advanced users in mind.
  fontawesome_icon_name: "paint-brush"

- title: Effortless Setup
  description: Automatically discover and connect to MPD servers on your network, making setup a breeze. Connect to all your devices without the hassle.
  fontawesome_icon_name: "wifi"

- title: Intuitive Library Navigation
  description: Quickly find and play your favorite tracks with a library browser and robust song search. Manage playlists, queue songs, and easily browse your library with intuitive features that make music discovery enjoyable and hassle-free.
  fontawesome_icon_name: folder-open

- title: Flexible Playback Options
  description: Play music directly on your device or send it to AirPlay and Bluetooth speakers. Suports popular formats like FLAC, MP3, and more, for a seamless listening experience.
  fontawesome_icon_name: "volume-up"

- title: Designed for HiFi Enthusiasts
  description: Perfect for audiophiles who value high-quality sound and easy access to their MPD servers. MPD Pilot brings top-tier playback and control directly to your iOS device.
  fontawesome_icon_name: "music"

- title: Learn More
  description: Find out more about MPD Pilot’s capabilities and why it’s ideal for your music collection. <a href="/features" target="_self">Learn more</a>
  fontawesome_icon_name: "question-circle"


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"


####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
  - vendor/
  - serve.sh
  - thumbnails.sh

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
